import { supabase } from "@/integrations/supabase/client";
// Phase 7 demo verification service. In-memory only (resets on reload).
// Swap these functions for API calls (FastAPI / PostGIS) later without touching the UI.

export type Pt = [number, number];
export type ReviewStatus = "Ready for Review" | "In Review" | "Changes Proposed" | "Accepted" | "Rejected" | "Returned for Evidence";
export type Role = "Viewer" | "Investigator" | "Reviewer" | "Administrator";

export type CandidateAttributes = Record<string, string>;
export type CandidateVersion = { v: number; geometry: Pt[]; attributes: CandidateAttributes; changes: string[]; reviewer: string; at: string };
export type VerificationEvent = { type: string; detail: string; reviewer: string; at: string; version: number };
export type ReviewerDecision = { decision: "Accept" | "Reject" | "Return for Evidence"; reason: string; note: string; evidence: string[]; version: number; reviewer: string; at: string };
export type AcceptedDifference = { conflict: string; status: "Resolved" | "Accepted as Difference" | "Unresolved" | "Not Applicable"; reason: string };
export type VerifiedRecord = { id: string; parcel: string; geometry: Pt[]; attributes: CandidateAttributes; version: number; reviewer: string; at: string; differences: AcceptedDifference[]; sources: string[] };

export type VerificationItem = {
  id: string; parcel: string; location: string; conflicts: string[]; severity: "Critical" | "High" | "Medium" | "Low";
  evidence: number; confidence: number; sources: { name: string; geometry: Pt[]; attributes: CandidateAttributes }[];
  harmonization: string; updated: string; reviewer: string; status: ReviewStatus;
  versions: CandidateVersion[]; events: VerificationEvent[]; decision?: ReviewerDecision; verified?: VerifiedRecord;
};

export const REVIEWER = "A. Raghavan (demo reviewer)";
export const CURRENT_ROLE: Role = "Reviewer";

const P: Record<Role, string[]> = {
  Viewer: ["view"],
  Investigator: ["view", "evidence"],
  Reviewer: ["view", "evidence", "edit", "verify", "reject", "return"],
  Administrator: ["view", "evidence", "edit", "verify", "reject", "return"],
};
export const can = {
  editCandidate: (r: Role) => P[r].includes("edit"),
  verifyRecord: (r: Role) => P[r].includes("verify"),
  rejectCandidate: (r: Role) => P[r].includes("reject"),
  returnForEvidence: (r: Role) => P[r].includes("return"),
  viewEvidence: (r: Role) => P[r].includes("evidence"),
};

const sq = (x: number, y: number, w: number, h: number): Pt[] => [[x, y], [x + w, y], [x + w, y + h], [x, y + h]];
const now = () => new Date().toISOString();

function make(id: string, parcel: string, location: string, conflicts: string[], severity: VerificationItem["severity"], status: ReviewStatus, dx: number): VerificationItem {
  const a = sq(60, 50, 200, 140), b = sq(60 + dx, 44, 204, 142), cand = sq(60 + dx / 2, 47, 202, 141);
  const aa = { parcel_id: parcel, land_use: "Residential", area: "1,245.2 m²", survey_no: "112/3A" };
  const ba = { parcel_id: parcel.replace("P-", ""), land_use: "Residential", area: "1,251.8 m²", survey_no: "—" };
  const ca = { parcel_id: parcel, land_use: "Residential", area: "1,248.4 m²", survey_no: "112/3A" };
  return {
    id, parcel, location, conflicts, severity, evidence: 60 + conflicts.length * 8, confidence: 0.7 + dx / 100,
    sources: [{ name: "Revenue (Source A)", geometry: a, attributes: aa }, { name: "Municipal (Source B)", geometry: b, attributes: ba }],
    harmonization: "Candidate generated", updated: "2h ago", reviewer: REVIEWER, status,
    versions: [{ v: 1, geometry: cand, attributes: ca, changes: ["Generated by harmonization engine"], reviewer: "System", at: now() }],
    events: [],
  };
}

let store: VerificationItem[] = [
  make("VR-2201", "P-10482", "Ward 12", ["Boundary Difference"], "High", "Ready for Review", 12),
  make("VR-2202", "P-10490", "Ward 12", ["Overlap", "Attribute Conflict"], "Critical", "Ready for Review", 18),
  make("VR-2203", "P-10501", "Ward 14", ["Gap"], "Medium", "In Review", 8),
  make("VR-2204", "P-10512", "Ward 15", ["Land-Use Conflict"], "High", "Changes Proposed", 10),
  make("VR-2205", "P-10520", "Ward 14", ["Attribute Conflict"], "Low", "Returned for Evidence", 4),
];

const SEED = store;
let loaded = false;
const listeners = new Set<() => void>();
let dirty: string | null = null;
let pendingEvent: VerificationEvent | null = null;
const emit = () => {
  store = [...store];
  const id = dirty, ev = pendingEvent; dirty = null; pendingEvent = null;
  const it = id ? store.find((i) => i.id === id) : null;
  if (it) {
    void supabase.from("verification_items").upsert({ id: it.id, data: it as never, updated_at: new Date().toISOString() }).then(({ error }) => error && console.error("Save failed", error.message));
    if (ev) void supabase.from("verification_events").insert({ item_id: it.id, type: ev.type, detail: ev.detail, reviewer: ev.reviewer, version: ev.version, at: ev.at }).then(({ error }) => error && console.error("Audit write failed", error.message));
  }
  listeners.forEach((l) => l());
};
/** Loads saved review state from Lovable Cloud. Call after hydration. */
export function loadPersisted() {
  if (loaded || typeof window === "undefined") return;
  loaded = true;
  void supabase.from("verification_items").select("id,data").then(({ data, error }) => {
    if (error || !data?.length) return;
    const saved = new Map(data.map((r) => [r.id, r.data as unknown as VerificationItem]));
    store = store.map((i) => saved.get(i.id) ?? i);
    listeners.forEach((l) => l());
  });
}
export function resetDemoData() {
  store = SEED.map((i) => ({ ...i }));
  void supabase.from("verification_items").delete().neq("id", "");
  listeners.forEach((l) => l());
}
export const subscribe = (l: () => void) => { listeners.add(l); return () => { listeners.delete(l); }; };

export const getVerificationQueue = () => store;
export const getAllEvents = () => store.flatMap((i) => i.events.map((e) => ({ ...e, item: i.id, parcel: i.parcel }))).sort((a, b) => b.at.localeCompare(a.at));
export const getVerifiedRecords = () => store.filter((i) => i.verified);
export const getVerificationItem = (id: string) => store.find((i) => i.id === id);
export const getCandidateVersion = (it: VerificationItem, v?: number) => (v ? it.versions.find((x) => x.v === v) : it.versions[it.versions.length - 1])!;
export const getVersionHistory = (it: VerificationItem) => it.versions;
export const getReviewEvents = (it: VerificationItem) => it.events;
export const getVerifiedRecord = (it: VerificationItem) => it.verified;

function update(id: string, fn: (i: VerificationItem) => VerificationItem, type: string, detail: string) {
  const it = getVerificationItem(id);
  if (!it) throw new Error("Candidate unavailable");
  const next = fn(it);
  const ev = { type, detail, reviewer: REVIEWER, at: now(), version: getCandidateVersion(next).v };
  next.events = [...next.events, ev];
  store = store.map((i) => (i.id === id ? next : i));
  dirty = id; pendingEvent = ev;
  emit();
}

export function startReviewSession(id: string) {
  update(id, (i) => ({ ...i, status: i.status === "Ready for Review" ? "In Review" : i.status }), "Candidate opened", "Review session started");
}

export function createCandidateVersion(id: string, geometry: Pt[], attributes: CandidateAttributes, changes: string[]) {
  update(id, (i) => ({ ...i, status: "Changes Proposed", versions: [...i.versions, { v: i.versions.length + 1, geometry, attributes, changes, reviewer: REVIEWER, at: now() }] }), "Candidate modified", changes.join("; "));
}
export const updateCandidateGeometry = (id: string, g: Pt[], summary: string) => {
  const c = getCandidateVersion(getVerificationItem(id)!);
  createCandidateVersion(id, g, c.attributes, [`Geometry changed: ${summary}`]);
};
export const updateCandidateAttribute = (id: string, field: string, value: string, reason: string) => {
  const c = getCandidateVersion(getVerificationItem(id)!);
  createCandidateVersion(id, c.geometry, { ...c.attributes, [field]: value }, [`${field}: "${c.attributes[field]}" → "${value}" (reason: ${reason})`]);
};
export const addNote = (id: string, note: string) => update(id, (i) => i, "Note added", note);

function decide(id: string, d: Omit<ReviewerDecision, "version" | "reviewer" | "at">, status: ReviewStatus, extra?: (i: VerificationItem) => Partial<VerificationItem>) {
  if (!d.reason.trim()) throw new Error("A reason is required");
  update(id, (i) => ({ ...i, status, decision: { ...d, version: getCandidateVersion(i).v, reviewer: REVIEWER, at: now() }, ...(extra?.(i) ?? {}) }), d.decision === "Accept" ? "Accepted" : d.decision === "Reject" ? "Rejected" : "Returned for evidence", `${d.reason}${d.note ? ` — ${d.note}` : ""}`);
}

export function acceptCandidate(id: string, reason: string, note: string, differences: AcceptedDifference[]) {
  if (!can.verifyRecord(CURRENT_ROLE)) throw new Error("Permission denied");
  decide(id, { decision: "Accept", reason, note, evidence: [] }, "Accepted", (i) => {
    const c = getCandidateVersion(i);
    return { verified: { id: `VREC-${i.parcel}`, parcel: i.parcel, geometry: c.geometry, attributes: c.attributes, version: c.v, reviewer: REVIEWER, at: now(), differences, sources: i.sources.map((s) => s.name) } };
  });
}
export const rejectCandidate = (id: string, reason: string, note: string) => decide(id, { decision: "Reject", reason, note, evidence: [] }, "Rejected");
export const submitForEvidence = (id: string, gap: string, note: string) => decide(id, { decision: "Return for Evidence", reason: gap, note, evidence: [] }, "Returned for Evidence");

export const polyArea = (g: Pt[]) => Math.abs(g.reduce((s, [x, y], i) => { const [x2, y2] = g[(i + 1) % g.length]!; return s + x * y2 - x2 * y; }, 0) / 2);
export const polyPerim = (g: Pt[]) => g.reduce((s, [x, y], i) => { const [x2, y2] = g[(i + 1) % g.length]!; return s + Math.hypot(x2 - x, y2 - y); }, 0);
